### ISSUE TITLE
relation "network.original_edges" does not exist

### ISSUE THREAD

**Issue by miaomiaomao** [cyang-kth/osm_mapmatching#2]
Hi, I'm new in using psql, so I meet this problem when creating schema and tables.
First, I met the problem "relation "network.original_edges" does not exist".
Then I use "CREATE TABLE network.original_edges()" and conduct "shp2pgsql data/stockholm/edges/edges.shp network.original_edges | psql -U postgres -d DATABASE" . 
But it didn't work and I met the problem "ERROR:  current transaction is aborted, commands ignored until end of transaction block".
Could you please tell me how to fix the problem? Very Thanks!

**Comment by cyang-kth** [comment]
@miaomiaomao 
Have you executed the command before importing network from shapefile 

```
# Create a schema called network
psql -U USERNAME -d DATABASE -c "CREATE SCHEMA network;"
```

Then make sure that the shapefile path is correct.

**Comment by miaomiaomao** [comment]
Thank you for your response.
I'm sure that my shapefile path is correct. And I conduct "psql -U USERNAME -d DATABASE -c "CREATE SCHEMA network;". Then I got the problem "relation "network.original_edges" does not exist" when I conduct shp2pgsql. 
 Is there any procedure between the above two procedures?
The whole description of the mistake is here:

> ERROR:  current transaction is aborted, commands ignored until end of transaction block

> ROLLBACK

> ERROR:  relation "network.original_edges" does not exist

**Comment by cyang-kth** [comment]
In your previous question, you said that you call this one

CREATE TABLE network.original_edges()

That command should not be called as the table is created automatically by executing `shp2pgsql` command. There is no other procedure between these two steps.

**Comment by miaomiaomao** [comment]
Thank you. If I carried `CREATE TABLE network.original_edges()` between the two procedures , the error is 

> ERROR: current transaction is aborted, commands ignored until end of transaction block

It seems that the problem is not here， maybe I should reload PostGIS and try again.
Thank you.

**Comment by cyang-kth** [comment]
@miaomiaomao 

I guess your problem is that the database does not exist. You need to create a database first. 

https://stackoverflow.com/questions/30641512/create-database-from-command-line
```
sudo -u postgres psql -c 'create database mm;'
```
Remember that when you execute command in shell, replace the `USERNAME` and `DATABASE` with your user name (postgres in the above example) and your database name (mm in the above example)

```
psql -U USERNAME -d DATABASE -c "CREATE SCHEMA network;"
```

**Comment by miaomiaomao** [comment]
Thank you.
I fixed problem by make my username consist with my system username.

**Comment by seewinds** [comment]
I ran into the same problem here. 

The command `shp2pgsql edges.shp network.test mm_db | psql -U apple -d mm_db` threw the errors that **'current transaction is aborted'** and **'relation does not exist'**.
However, the figure below indicates that the shapefile, database and schema do exist.

<img width="851" alt="pgsql" src="https://user-images.githubusercontent.com/17062094/76341152-9ad19900-6337-11ea-9041-3be67133d22a.png">

**Comment by cyang-kth** [comment]
@seewinds 

Could it be this problem that your command contains the extra database name
```
shp2pgsql edges.shp network.test **mm_db** | psql -U apple -d mm_db
```

compared with the instructions
```
# Import the downloaded edges and nodes shapefile.
shp2pgsql data/stockholm/edges/edges.shp network.original_edges | psql -U postgres -d mm_db
shp2pgsql data/stockholm/nodes/nodes.shp network.original_nodes | psql -U postgres -d mm_db
```

shp2pgsql will only generate the an SQL file with all the commands embedded so you should not give the database name there.

**Comment by seewinds** [comment]
No, I experimented with the following operations and their combinations,

- with and without `mm_db`
- explicitly set the option `-c` to create the new table (folowing the help doc of `shp2pgsql`)

The wierd thing is that none of these worked...

One finding is that when the second part of the command was dropped, i.e., 
```shp2pgsql edges.shp network.test```,
the ouput seemed to be correct (see the image below).
Therefore, it is suspected that the problem is not with `shp2pgsql`. Instead, it lies in the execution of those output commands in `psql`.
<img width="851" alt="no psql" src="https://user-images.githubusercontent.com/17062094/76376476-55d35400-6383-11ea-9c98-3d5a579a54eb.png">

**Comment by seewinds** [comment]
Successfully resolved :sweat:
After creating the database, I forgot to enable the PostGIS extension.
```
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
```

**Comment by cyang-kth** [comment]
@seewinds 

Great! I will add these into the instructions.
